### ISSUE TITLE
CP-2158 Investigate API for updating/replacing upload/download progress streams

### ISSUE THREAD

**Issue by evanweible-wf** [Workiva/w_service#53]
Possible use case: interceptor that wants to consolidate multiple requests and thus wants to override the upload/download progress streams.

Should this be done in an interceptor? Or is this too closely tied to a specific server implementation that it should be done in a provider?

**Comment by trentgrover-wf** [comment]
w_service is deprecated - use [w_transport](https://github.com/Workiva/w_transport) instead
