### ISSUE TITLE
CP-2156 CsrfInterceptor: Add stream for CSRF token change events

### ISSUE THREAD

**Issue by evanweible-wf** [Workiva/w_service#56]
```dart
StreamController<String> _onTokenChange = new StreamController<String>();
Stream<String> _onTokenChangeStream = _onTokenChange.stream.asBroadcastStream();
String _token = '';

Stream<String> get onTokenChange => _onTokenChangeStream;
String get token => _token;
set token(String token) {
  _token = token;
  _onTokenChange.add(token);
}
```

Would allow whoever creates the `CsrfInterceptor` to listen to whenever the token is updated. Thoughts?
@trentgrover-wf @maxwellpeterson-wf

**Comment by trentgrover-wf** [comment]
Do you have a use case in mind?

I have no objection, but just keep in mind that whatever you add to a public API is likely ours to maintain forever.

**Comment by evanweible-wf** [comment]
Potentially within w_session.. I'm adding it to the workiva-specific CsrfInterceptor right now and I'll see how it looks/if I like it.

**Comment by trentgrover-wf** [comment]
w_service is deprecated - use [w_transport](https://github.com/Workiva/w_transport) instead
