### ISSUE TITLE
CP-2154 HttpFutures will be effectively converted back to _Future when returned from `async` method

### ISSUE THREAD

**Issue by evanweible-wf** [Workiva/w_service#68]
A method with the `async` keyword ensure that the return type is a future. It does this by checking if the type of the item returned is `_Future` and `HttpFuture` doesn't pass that check, which means returning an `HttpFuture` from an `async` method will convert the future back to `_Future`, removing the `HttpFuture` API

**Comment by trentgrover-wf** [comment]
w_service is deprecated - use [w_transport](https://github.com/Workiva/w_transport) instead
